# Generated by Django 5.2.1 on 2025-05-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_livro_capa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editora',
            old_name='name',
            new_name='nome',
        ),
    ]
