# Generated by Django 5.2.1 on 2025-07-01 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('Carrinho', 'Carrinho'), ('Finalizado', 'Finalizado'), ('Pago', 'Pago'), ('Entregue', 'Entregue')], default='Carrinho')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
